### ISSUE TITLE
Change from DeploymentConfig to Deployment

### ISSUE THREAD

**Issue by lance** [nodeshift/nodeshift#228]
The latest versions of OpenShift Origin support all of the features of `DeploymentConfig` in the [`v1beta1` API](https://docs.openshift.com/container-platform/3.9/rest_api/apis-apps/v1beta1.Deployment.html).

In working with Istio, I have found that it uses `Deployment` objects instead of `DeploymentConfig`. In order to make sidecar injection work in a simple, 2-step process I would like to do the following. 

```
istioctl kube-inject -f .nodeshift/deployment.yml > .nodeshift/deployment.yml
nodeshift --strictSSL=false --nodeVersion=10.x --expose
```

This should inject all of the Istio sidecar capabilities into whatever deployment config we have for a given project. The `istioctl` process will merge its stuff with ours. It changes the `apiVersion` attribute, however, it doesn't change the `kind` attribute from `DeploymentConfig` to `Deployment` and when I run `nodeshift` with the resulting `yaml` file, I get this error.

```log
2018-05-22T21:09:25.760Z ERROR {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"DeploymentConfig in version \"v1beta1\" cannot be handled as a DeploymentConfig: no kind \"DeploymentConfig\" is registered for version \"extensions/v1beta1\"","reason":"BadRequest","code":400}
2018-05-22T21:09:25.761Z ERROR Status code 400
```

I think it might be as simple as changing [this](https://github.com/bucharest-gold/nodeshift/blob/master/lib/resource-enrichers/deployment-config-enricher.js#L28-L31) but I'm not entirely sure.

This might be a semver major change? I don't know when OpenShift started supporting `Deployment` and when that schema included all of the attributes of a `DeploymentConfig`. But some older OpenShift versions might break with this change.

**Comment by lholmquist** [comment]
I think this is the part that converts it to a DeploymentConfig, https://github.com/bucharest-gold/nodeshift/blob/master/lib/resource-enrichers/deployment-config-enricher.js#L62

Since we were just doing Openshift stuff, it made sense at the time.  But now, we should probably change it.  I think we would need to figure out if this is just an Openshift deploy or an Istio deploy and then update if needed

I think we might need to also update the Openshift-rest-client. I don't think it knows about the Deployment API's

This will definitely be a semver major change.

**Comment by lholmquist** [comment]
Looks like this API is still there in 3.7, https://docs.openshift.com/container-platform/3.7/rest_api/apis-apps/v1beta1.Deployment.html

**Comment by lance** [comment]
Closing for lack of movement. May revisit someday.
