### ISSUE TITLE
Enhancement: ability to specify output image name

### ISSUE THREAD

**Issue by lance** [nodeshift/nodeshift#337]
It would be nice to have the ability to give a name to the output image from the `build` task. It's nice that nodeshift already uses the `name` from `package.json`. But it would be good for pipelines to be able to specify a given run what the output image name - for example `my-webapp-staging` and `my-webapp-production`.

**Comment by lholmquist** [comment]
This would be a nice addition and it sort of goes along with a TODO item that i've had in the code for a while around being able to specify a [tag name instead of just using latest](https://github.com/nodeshift/nodeshift/blob/master/lib/build-config.js#L82), 

Since we are always using latest,  we are overwriting the previous "version" of the imagestream during every build.

Another thing that might also make sense, is the ability to specify different buildConfigs?  Currently when you run `nodeshift` a default buildConfig is created, then this is used on subsequent calls to `nodeshift` unless the flag to recreate is specified.  It could be interesting if you had the ability to specify a previously created buildConfig without having to re-create each time


I'm sort of hijacking this issue, but i think they logically go together.

**Comment by lance** [comment]
@lholmquist @helio-frota I think the implementation for the image name + tag could be very simple. E.g.

```js
config.outputImageTag = config.outputImageTag ? config.outputImageTag : 'latest';
const outputImageStreamTag = `${config.outputImage}:${config.outputImageTag}`;
```

And of course, adding `outputImage` and `outputImageTag` as command line options so they end up on the `config` object.

I think the flexibility you'd get by naming the `BuildConfig` would be nice. But yeah, that's a different issue. :)
