### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodeshift#339]
https://github.com/nodeshift/nodeshift/blob/master/lib/helpers.js#L30

**Comment by lholmquist** [comment]
probably still a good idea.

**Comment by helio-frota** [comment]
@lholmquist the tests for this function are mocked so the function is not actually called.
You mean simply try and throw a parsing error message for this case?

**Comment by lholmquist** [comment]
The test should be "what happens if that function throws an error while parsing".  Since all of Nodeshift is wrapped in a Promise, the error should end up in the catch function.

So maybe we don't really need to do any error handling here.  We don't need to test the functionality of the function it uses, https://www.npmjs.com/package/js-yaml#safeload-string---options-, since that library is already probably testing it.

I would say we could remove that TODO and just close this issue then
