### ISSUE TITLE
nodeshift not adding package.json inside tar file

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodeshift#453]
How to reproduce:

Clone https://github.com/nodeshift-starters/nodejs-rest-http
Remove package.json from `files` section

I can't say that is a bug since I don't know when this feature of always add certain known files was added to npm. https://docs.npmjs.com/files/package.json#files

**Comment by lholmquist** [comment]
I don't think this is a bug.  Nodeshift either tar's the files a user specifies in the package.jsons `files` property or it tar's the current working directory(minus node_modules/.git/tmp/etc..) if the `files` prop is missing.

It doesn't work like npm, where certain files will always be included if they are there.

Since nodeshift deals with node applications, we might be able to assume users want to include the package.json, so we could add something that does that by default.

**Comment by helio-frota** [comment]
`Since nodeshift deals with node applications, we might be able to assume users want to include the package.json, so we could add something that does that by default.`

sounds good to me :+1:

**Comment by lholmquist** [comment]
That should be a pretty straightforward addition
