### ISSUE TITLE
quiet option not working as expected

### ISSUE THREAD

**Issue by helio-frota** [nodeshift/nodeshift#488]
When using `--quiet` nodeshift should suppress `info` and `trace` logs.
That is not working because common-log.js is getting required before yargs start processing the arguments.

**Comment by lholmquist** [comment]
Nice catch,   I feel like I might have changed this for some reason, and didn't realize it broke something.  if you do a `git blame` i bet you will see my name :)

**Comment by helio-frota** [comment]
So I was not able to workaround, but 3 years ago this part of the code was added `.env('NODESHIFT')`, 
https://github.com/nodeshift/nodeshift/blob/master/bin/nodeshift#L72
and when we use `NODESHIFT_QUIET=true` , yargs  can make use of it to effectively suppress the logs
https://yargs.js.org/docs/ 
> .env([prefix])
Tell yargs to parse environment variables matching the given prefix and apply them to argv as though they were command line arguments.
 
It seems that something happened over the time... 
so IMO we should just remove `--quiet` from the docs/options
and add a small section "If you want to suppress info and trace logs , use `NODESHIFT_QUIET=true`

wdyt @lholmquist ?

**Comment by lholmquist** [comment]
could you try reverting what i did in this commit, https://github.com/nodeshift/nodeshift/commit/fca4ad8f73f54808e5de504ab865b03a124561f3

I think this might have broken it.   I moved both the cli and log require to the top of the file, instead of requiring them in the cmdHandler function.    Moving them to the top would load both of those files first, before any of the options where parsed, so it might work if those are put back

**Comment by helio-frota** [comment]
thanks for the suggestion :+1:
